### ISSUE TITLE
what is "Give: XKE"

### ISSUE THREAD

**Issue by KissBalazs** [shekhargulati/building-java-web-apps-checklist#1]
I could not figure that one out. Great list though, thank you!

**Comment by shekhargulati** [comment]
@KissBalazs I prepared this checklist for an internal talk at my current employer Xebia. In Xebia, we have a concept of XKE(Xebia Knowledge Exchange). Every alternate Thursday we have two hours of knowledge sharing sessions. I have update the checklist.

**Comment by KissBalazs** [comment]
Thank you for the detailed answer!
